kind: github
version: v3
metadata:
  name: github
spec:
  client_id: ${client_id}
  client_secret: ${client_secret}
  display: Github
  redirect_url: https://${proxy_domain}/v1/webapi/github/callback
  teams_to_logins:
    - organization: adhocteam
      team: infrastructure-team
      logins:
        - ec2-user