teleport:
  nodename: ${nodename}
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport/teleport.pid
  auth_token: ${cluster_token}
  auth_servers:
  - auth.teleport.local:3025
  connection_limits:
    max_connections: 100
    max_users: 50
  log:
    output: stderr
    severity: INFO
  storage:
    type: dynamodb
    region: ${region}
    table_name: ${dynamo_table_name}
    audit_events_uri: dynamodb://${dynamo_events_table_name}
    audit_sessions_uri: s3://${s3_bucket}/records
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  tokens:
  - "auth,proxy,node:${cluster_token}"
  cluster_name: ${cluster_name}
  session_recording: "node"
  client_idle_timeout: "1h"
  disconnect_expired_cert: "yes"
  authentication:
    type: github
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"