#!/bin/bash

# Setup teleport auth server config file
INSTANCE_ID=$(curl -sSf http://169.254.169.254/latest/meta-data/instance-id)
REGION=$(curl -sSf http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/.$//')
ENVIRONMENT=$(aws ec2 describe-tags --region "$REGION" --filters "Name=resource-id,Values=${INSTANCE_ID}" | jq '.Tags | .[] | select(.Key | contains("env")) | .Value ' | cut -f 2 -d '"')
SECRET_ID="${ENVIRONMENT}/teleport/cluster_token"

NODENAME=$(aws ec2 describe-tags --region "$REGION" --filters "Name=resource-id,Values=${INSTANCE_ID}" | jq '.Tags | .[] | select(.Key | contains("Name")) | .Value ' | cut -f 2 -d '"')
CLUSTER_TOKEN=$(aws secretsmanager get-secret-value --region "$REGION" --secret-id ${SECRET_ID} | jq ".SecretString" | cut -f 2 -d '"')

sed -i "s/{{ nodename }}/${NODENAME}/g" /etc/teleport.yaml
sed -i "s/{{ cluster_token }}/${CLUSTER_TOKEN}/g" /etc/teleport.yaml