global:
  scrape_interval: 15s
  evaluation_interval: 30s

  scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']
          
    - job_name: 'jenkins'
      static_configs:
        - targets: ['https://jenkins.adhoc.team/prometheus/']

    - job_name: 'teleport'
      ec2_sd_configs:
        - region: us-east-1
          port: 3434
          
    - job_name: 'node'
      ec2_sd_configs:
        - region: us-east-1
          port: 9100
