global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAIOHITDOVPKCEL3GQ
        secret_key: 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
        port: 9100